name: flutter_youtube_player
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: '>=2.8.0-dev <3.0.0'
  flutter: '>=3.0.0 <4.0.0'
dependencies:
  cupertino_icons:
  disposable_provider:
  flutter:
    sdk: flutter
  google_fonts:
  intl:
  mono_kit:
  provider:
  simple_logger:
  timeago:
  touch_indicator:
  vsync_provider:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
flutter:
  uses-material-design: true
  assets:
    - assets/images/
